name: Build and optionally Publish Docker Images

on:
  workflow_call:
    inputs:
      docker-name:
        description: 'Name of folder in the "docker" directory in this repository'
        required: true
        type: string
      dockerfile:
        description: 'Name of the docker file to use'
        required: true
        type: string
      tag-prefix:
        type: string
        default: ''
      platform:
        description: 'Docker build platform'
        type: string        
        default: linux/amd64
      publish:
        description: 'Whether to publish the image as well'
        required: true
        type: boolean
      runs-on:
        description: 'Host OS'
        default: ubuntu-latest
        type: string

concurrency:
  group: build-docker-${{ inputs.docker-name }}-${{ inputs.tag-prefix }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build-image:
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Build and push Docker image
        id: push
        uses: mr-smithers-excellent/docker-build-push@59523c638baec979a74fea99caa9e29d97e5963c # v6.4
        with:        
          dockerfile: ${{ inputs.dockerfile }}
          image: ${{ inputs.docker-name }}
          tags: ${{ inputs.tag-prefix }}latest, ${{ inputs.tag-prefix }}${{ github.sha }}
          platform: ${{ inputs.platform }}
          registry: ghcr.io
          pushImage: ${{ inputs.publish }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
